name: CI

on:
  push:
    branches: ["*"]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
          cache: true
          cache-dependency-path: '**/packages.lock.json'

      - name: Restore
        run: |
          dotnet restore EasyCLI/EasyCLI.csproj --verbosity detailed --locked-mode || dotnet restore EasyCLI/EasyCLI.csproj --verbosity detailed
          dotnet restore EasyCLI.Tests/EasyCLI.Tests.csproj --verbosity detailed --locked-mode || dotnet restore EasyCLI.Tests/EasyCLI.Tests.csproj --verbosity detailed
          dotnet restore EasyCLI.Demo/EasyCLI.Demo.csproj --verbosity detailed --locked-mode || dotnet restore EasyCLI.Demo/EasyCLI.Demo.csproj --verbosity detailed

      - name: Build (Library)
        run: dotnet build EasyCLI/EasyCLI.csproj --configuration Release --no-restore

      - name: Build (Demo)
        run: dotnet build EasyCLI.Demo/EasyCLI.Demo.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test EasyCLI.Tests/EasyCLI.Tests.csproj --configuration Release --no-restore --verbosity minimal
