name: DEPRECATED publish workflow (inactive)

# This workflow is intentionally disabled. Use version-tag-publish.yml instead.
# Retained only so historical references to publish.yml do not 404.

on: workflow_dispatch

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: Notice
        run: |
          echo 'Deprecated publish.yml workflow. Use Version, Tag & Publish workflow.'
