name: Release Branch Bootstrap & Publish (GitHub Packages)

# When a release/* branch is CREATED, automatically:
# 1. Derive version from branch name (release/<version>)
# 2. Update csproj <Version> (commit to the branch)
# 3. Create and push git tag v<version>
# 4. Restore, build, test, pack
# 5. Publish nupkg to GitHub Packages ONLY
# 6. Create GitHub Release (prerelease flag if version contains '-')

on:
  create:
  push:
    branches:
      - 'release/**'

permissions:
  contents: write
  packages: write

jobs:
  init:
    name: Init (derive version, update csproj, ensure tag)
    runs-on: ubuntu-latest
    if: >-
      (github.event_name == 'create' && github.event.ref_type == 'branch' && startsWith(github.event.ref, 'release/'))
    outputs:
      version: ${{ steps.derive.outputs.version }}
      tag_created: ${{ steps.tag.outputs.created || 'false' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Derive version from branch name
        id: derive
        run: |
          if [ "${GITHUB_EVENT_NAME}" = 'create' ]; then
            raw_ref='${{ github.event.ref }}'
          else
            raw_ref="${GITHUB_REF_NAME}"
          fi
          version="${raw_ref#release/}"
          if [ -z "$version" ]; then
            echo 'Could not parse version from branch name' >&2; exit 1
          fi
          if ! echo "$version" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?$'; then
            echo "Branch version '$version' is not valid SemVer (X.Y.Z or X.Y.Z-prerelease)" >&2; exit 1
          fi
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "Derived version: $version"

      - name: Update csproj version
        run: |
          ver='${{ steps.derive.outputs.version }}'
          csproj='EasyCLI/EasyCLI.csproj'
          safe=$(printf '%s' "$ver" | sed -e 's/[\\/&]/\\&/g')
          if grep -q "<Version>$safe</Version>" "$csproj"; then
            echo "csproj already at $ver"
          else
            if grep -q '<Version>[^<]*</Version>' "$csproj"; then
              sed -i.bak -E "s#<Version>[^<]+</Version>#<Version>$safe</Version>#" "$csproj" || { echo 'Failed to replace version'; exit 1; }
            else
              sed -i.bak -E "s#</PropertyGroup>#  <Version>$safe</Version>\n  </PropertyGroup>#" "$csproj" || { echo 'Failed to insert version'; exit 1; }
            fi
            rm -f "$csproj.bak"
            git config user.name 'github-actions'
            git config user.email 'github-actions@users.noreply.github.com'
            git add "$csproj"
            git commit -m "chore: set/align release version $ver" || echo 'No changes to commit'
            git push || true
          fi

      - name: Ensure tag
        id: tag
        run: |
          ver='${{ steps.derive.outputs.version }}'
          git fetch --tags --quiet || true
          if git rev-parse "v$ver" >/dev/null 2>&1; then
            echo "Tag v$ver already exists"; echo "created=false" >> $GITHUB_OUTPUT
          else
            git tag "v$ver"
            git push origin "v$ver"
            echo "created=true" >> $GITHUB_OUTPUT
          fi

      - name: Summary
        run: |
          echo "## Init" >> $GITHUB_STEP_SUMMARY
          echo "Version: ${{ steps.derive.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "Tag created: ${{ steps.tag.outputs.created }}" >> $GITHUB_STEP_SUMMARY

  test:
    name: Test (restore, build, test)
    needs: init
    if: needs.init.outputs.version != ''
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache NuGet
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: nuget-${{ runner.os }}-${{ hashFiles('**/packages.lock.json') }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
          cache: true
          cache-dependency-path: '**/packages.lock.json'

      - name: Restore
        run: |
          set -e
          echo "Restoring (locked mode) library & tests"
          dotnet restore EasyCLI/EasyCLI.csproj --locked-mode
          dotnet restore EasyCLI.Tests/EasyCLI.Tests.csproj --locked-mode

      - name: Build
        run: dotnet build EasyCLI/EasyCLI.csproj -c Release --no-restore

      - name: Test
        run: dotnet test EasyCLI.Tests/EasyCLI.Tests.csproj -c Release --no-restore --verbosity minimal

      - name: Upload library build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lib-build-release
          path: |
            EasyCLI/bin/Release/
            EasyCLI/obj/

      - name: Summary
        run: |
          echo "## Test" >> $GITHUB_STEP_SUMMARY
          echo "Version: ${{ needs.init.outputs.version }}" >> $GITHUB_STEP_SUMMARY

  publish:
    name: Publish (pack, GitHub Packages, release)
    needs: [test, init]
    if: needs.init.outputs.version != ''
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
          cache: true
          cache-dependency-path: '**/packages.lock.json'
      
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: lib-build-release
          path: .

      - name: Verify build artifacts
        run: |
          echo "Listing downloaded artifact contents (top-level):"
          find EasyCLI/bin/Release -maxdepth 3 -type f -name '*.dll' -print || true
          if [ ! -f EasyCLI/bin/Release/net9.0/EasyCLI.dll ]; then
            echo 'Missing built DLL after artifact download; performing on-demand restore+build fallback.'
            dotnet restore EasyCLI/EasyCLI.csproj --locked-mode || dotnet restore EasyCLI/EasyCLI.csproj
            dotnet build EasyCLI/EasyCLI.csproj -c Release --no-restore
          fi
          if [ ! -f EasyCLI/bin/Release/net9.0/EasyCLI.dll ]; then
            echo 'Still missing EasyCLI.dll after fallback build.' >&2
            ls -R EasyCLI/bin/Release || true
            exit 1
          fi
          ls -1 EasyCLI/bin/Release/net9.0

      - name: Pack
        run: dotnet pack EasyCLI/EasyCLI.csproj -c Release --no-build -p:ContinuousIntegrationBuild=true -o dist

      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dotnet nuget remove source github 2>/dev/null || true
          dotnet nuget add source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            --name github \
            --username "${{ github.repository_owner }}" \
            --password "${GITHUB_TOKEN}" \
            --store-password-in-clear-text
          for pkg in dist/*.nupkg; do
            echo "Pushing $pkg to GitHub Packages";
            dotnet nuget push "$pkg" --api-key "${GITHUB_TOKEN}" --source github --skip-duplicate;
          done

      - name: Create / Update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.init.outputs.version }}
          name: EasyCLI v${{ needs.init.outputs.version }}
          prerelease: ${{ contains(needs.init.outputs.version, '-') }}
          generate_release_notes: true
          files: dist/*.nupkg

      - name: Summary
        run: |
          echo "## Publish" >> $GITHUB_STEP_SUMMARY
          echo "Version: ${{ needs.init.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "Tag: v${{ needs.init.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "Packages:" >> $GITHUB_STEP_SUMMARY
          ls -1 dist >> $GITHUB_STEP_SUMMARY
  update_init:
    name: Update Init (version, csproj, tag)
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/release/') && github.event_name != 'create'
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.derive.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Derive version from branch name
        id: derive
        run: |
          raw_ref='${GITHUB_REF_NAME}'
          version="${raw_ref#release/}"
          if [ -z "$version" ]; then
            echo 'Could not parse version from branch name' >&2; exit 1
          fi
          if ! echo "$version" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?$'; then
            echo "Branch version '$version' is not valid SemVer (X.Y.Z or X.Y.Z-prerelease)" >&2; exit 1
          fi
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "Derived version: $version"

      - name: Ensure csproj version
        run: |
          ver='${{ steps.derive.outputs.version }}'
          csproj='EasyCLI/EasyCLI.csproj'
          if grep -q "<Version>$ver</Version>" "$csproj"; then
            echo "csproj already at $ver"
          else
            safe=$(printf '%s' "$ver" | sed -e 's/[\\/&]/\\&/g')
            if grep -q '<Version>[^<]*</Version>' "$csproj"; then
              sed -i.bak -E "s#<Version>[^<]+</Version>#<Version>$safe</Version>#" "$csproj" || { echo 'Failed to replace version'; exit 1; }
            else
              sed -i.bak -E "s#</PropertyGroup>#  <Version>$safe</Version>\n  </PropertyGroup>#" "$csproj" || { echo 'Failed to insert version'; exit 1; }
            fi
            rm -f "$csproj.bak"
            git config user.name 'github-actions'
            git config user.email 'github-actions@users.noreply.github.com'
            git add "$csproj"
            git commit -m "chore: align release version $ver" || echo 'No changes to commit'
            git push || true
          fi

      - name: Ensure tag
        run: |
          ver='${{ steps.derive.outputs.version }}'
          git fetch --tags --quiet || true
          if git rev-parse "v$ver" >/dev/null 2>&1; then
            echo "Tag v$ver already present"
          else
            git tag "v$ver"
            git push origin "v$ver"
          fi

      - name: Summary
        run: |
          echo "## Update Init" >> $GITHUB_STEP_SUMMARY
          echo "Version: ${{ steps.derive.outputs.version }}" >> $GITHUB_STEP_SUMMARY

  update_test:
    name: Update Test (restore, build, test)
    needs: update_init
    if: needs.update_init.outputs.version != ''
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache NuGet
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: nuget-${{ runner.os }}-${{ hashFiles('**/packages.lock.json') }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
          cache: true
          cache-dependency-path: '**/packages.lock.json'

      - name: Restore
        run: |
          set -e
          echo "Restoring (locked mode) library & tests"
          dotnet restore EasyCLI/EasyCLI.csproj --locked-mode
            dotnet restore EasyCLI.Tests/EasyCLI.Tests.csproj --locked-mode

      - name: Build
        run: dotnet build EasyCLI/EasyCLI.csproj -c Release --no-restore

      - name: Test
        run: dotnet test EasyCLI.Tests/EasyCLI.Tests.csproj -c Release --no-restore --verbosity minimal

      - name: Upload library build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lib-build-release
          path: |
            EasyCLI/bin/Release/
            EasyCLI/obj/

      - name: Summary
        run: |
          echo "## Update Test" >> $GITHUB_STEP_SUMMARY
          echo "Version: ${{ needs.update_init.outputs.version }}" >> $GITHUB_STEP_SUMMARY

  update_publish:
    name: Update Publish (pack, GitHub Packages, release)
    needs: [update_test, update_init]
    if: needs.update_init.outputs.version != ''
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
          cache: true
          cache-dependency-path: '**/packages.lock.json'
      
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: lib-build-release
          path: .

      - name: Verify build artifacts
        run: |
          echo "Listing downloaded artifact contents (top-level):"
          find EasyCLI/bin/Release -maxdepth 3 -type f -name '*.dll' -print || true
          if [ ! -f EasyCLI/bin/Release/net9.0/EasyCLI.dll ]; then
            echo 'Missing built DLL after artifact download; performing on-demand restore+build fallback.'
            dotnet restore EasyCLI/EasyCLI.csproj --locked-mode || dotnet restore EasyCLI/EasyCLI.csproj
            dotnet build EasyCLI/EasyCLI.csproj -c Release --no-restore
          fi
            if [ ! -f EasyCLI/bin/Release/net9.0/EasyCLI.dll ]; then
            echo 'Still missing EasyCLI.dll after fallback build.' >&2
            ls -R EasyCLI/bin/Release || true
            exit 1
          fi
          ls -1 EasyCLI/bin/Release/net9.0

      - name: Pack
        run: dotnet pack EasyCLI/EasyCLI.csproj -c Release --no-build --no-restore -p:ContinuousIntegrationBuild=true -o dist

      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dotnet nuget remove source github 2>/dev/null || true
          dotnet nuget add source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            --name github \
            --username "${{ github.repository_owner }}" \
            --password "${GITHUB_TOKEN}" \
            --store-password-in-clear-text
          for pkg in dist/*.nupkg; do
            echo "Pushing $pkg to GitHub Packages";
            dotnet nuget push "$pkg" --api-key "${GITHUB_TOKEN}" --source github --skip-duplicate;
          done

      - name: Create / Update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.update_init.outputs.version }}
          name: EasyCLI v${{ needs.update_init.outputs.version }}
          prerelease: ${{ contains(needs.update_init.outputs.version, '-') }}
          generate_release_notes: true
          files: dist/*.nupkg

      - name: Summary
        run: |
          echo "## Update Publish" >> $GITHUB_STEP_SUMMARY
          echo "Version: ${{ needs.update_init.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "Tag: v${{ needs.update_init.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "Packages:" >> $GITHUB_STEP_SUMMARY
          ls -1 dist >> $GITHUB_STEP_SUMMARY
